# PESKAS_0_Mock_Data.R
# Generates a structured mock CPUE dataset for validating PESKAS_1–3 code.
# Known counts and distributions mean you can verify any summary against
# expected values rather than guessing whether the code is correct.
#
# Design (same structure as mock_peskas_cpue.csv generated by Python):
#   4 municipalities × 82 months × 30 rows = 9,840 rows
#   Habitat : 15 Deep / 15 Reef per municipality per month
#   Gear    : 10 hand line / 10 long line / 10 gill net per municipality per month
#   Taxon   : TRV=8, SNA=8, SRD=7, MCK=7 per municipality per month
#   cpue    = tot_catch / (n_fishers × trip_length)  [landing-level]
#   cpue_fg = catch     / (n_fishers × trip_length)  [taxon-level]
#   One taxon per landing → tot_catch = catch → cpue = cpue_fg

# ── 1. Setup ──────────────────────────────────────────────────────────────────
library(tidyverse)
library(lubridate)

set.seed(42)

# ── 2. Reference tables ───────────────────────────────────────────────────────
municipalities <- c("Manufahi", "Covalima", "Ainaro", "Viqueque")

landing_sites <- list(
  Manufahi = c("Same", "Betano"),
  Covalima = c("Suai", "Fatululic"),
  Ainaro   = c("Ainaro", "Aituto"),
  Viqueque = c("Viqueque", "Uatolari")
)

# Taxon-level catch parameters (mean and sd in kg)
# Sardines highest (schooling); snapper lowest (demersal, less abundant)
fish_meta <- tibble(
  fish_grp    = c("trevally", "snapper", "sardines", "mackerel"),
  catch_taxon = c("TRV",      "SNA",     "SRD",      "MCK"),
  catch_name  = c("Trevally group", "Snapper group", "Sardines group", "Mackerel group"),
  catch_mu    = c(15, 10, 28, 18),
  catch_sd    = c(5,   4,  9,  6)
)

# ── 3. Fixed 30-row template (repeated every municipality × month) ─────────────
# Deep rows 1–5, Reef rows 6–10 within each gear block
# hand line (10) : trevally=3, snapper=3, sardines=2, mackerel=2
# long line (10) : trevally=3, snapper=2, sardines=3, mackerel=2
# gill net  (10) : trevally=2, snapper=3, sardines=2, mackerel=3
template <- tibble(
  row_idx  = 1:30,
  gear     = c(rep("hand line", 10), rep("long line", 10), rep("gill net", 10)),
  habitat  = rep(c(rep("Deep", 5), rep("Reef", 5)), 3),
  fish_grp = c(
    c("trevally","trevally","trevally","snapper","snapper",
      "snapper","sardines","sardines","mackerel","mackerel"),
    c("trevally","trevally","trevally","snapper","snapper",
      "sardines","sardines","sardines","mackerel","mackerel"),
    c("trevally","trevally","snapper","snapper","snapper",
      "sardines","sardines","mackerel","mackerel","mackerel")
  )
) %>%
  left_join(fish_meta, by = "fish_grp")

# Template checks — Expected: 10 per gear, 15 per habitat, TRV/SNA=8 SRD/MCK=7
stopifnot(
  all(table(template$gear)     == 10),
  all(table(template$habitat)  == 15),
  all(table(template$fish_grp) %in% c(7L, 8L))
)
cat("Template checks passed\n")

# ── 4. Month sequence: June 2018 to March 2025 — Expected: 82 months ──────────
month_seq <- seq(as.Date("2018-06-01"), as.Date("2025-03-01"), by = "month")
cat("Months:", length(month_seq), "\n")

# ── 5. Generate dataset ────────────────────────────────────────────────────────
mock_data <- map_dfr(municipalities, function(muni) {
  sites <- landing_sites[[muni]]
  map_dfr(seq_along(month_seq), function(m_idx) {
    mo     <- month_seq[m_idx]
    n_days <- as.integer(days_in_month(mo))
    template %>%
      mutate(
        landing_id      = sprintf("%s_%s_%02d", substr(muni, 1, 3),
                                  format(mo, "%Y%m"), row_idx),
        landing_date    = mo + sample(0L:(n_days - 1L), 30, replace = TRUE),
        municipality    = muni,
        landing_site    = sample(sites, 30, replace = TRUE),
        trip_length     = sample(4:12, 30, replace = TRUE),
        n_fishers       = sample(1:4,  30, replace = TRUE),
        catch           = round(pmax(1, rnorm(30, catch_mu, catch_sd)), 1),
        tot_catch       = catch,
        cpue            = round(tot_catch / (n_fishers * trip_length), 4),
        cpue_fish_group = round(catch     / (n_fishers * trip_length), 4)
      ) %>%
      select(landing_id, landing_date, municipality, landing_site,
             trip_length, n_fishers, gear, habitat,
             catch_taxon, catch_name, catch, tot_catch, cpue, cpue_fish_group)
  })
})

# ── 6. Verification checks ────────────────────────────────────────────────────
cat("\nTotal rows:", nrow(mock_data), "  | Expected: 9,840\n")

cat("\nRows per municipality  (Expected: 2,460 each):\n")
print(count(mock_data, municipality))

cat("\nHabitat per municipality  (Expected: 1,230 Deep / 1,230 Reef):\n")
print(count(mock_data, municipality, habitat))

cat("\nGear per municipality  (Expected: 820 each):\n")
print(count(mock_data, municipality, gear))

cat("\nTaxon per municipality  (Expected: TRV=656  SNA=656  SRD=574  MCK=574):\n")
print(count(mock_data, municipality, catch_taxon))

cat("\nDate range:", format(min(mock_data$landing_date)),
    "to", format(max(mock_data$landing_date)), "\n")

cat("\nMean catch and cpue_fish_group by taxon:\n")
mock_data %>%
  group_by(catch_taxon, catch_name) %>%
  summarise(mean_catch = round(mean(catch), 1),
            mean_cpue  = round(mean(cpue_fish_group), 3),
            .groups = "drop") %>%
  print()

# ── 7. Save ───────────────────────────────────────────────────────────────────
out_path <- here::here("Data", "raw", "Fisheries", "mock_peskas_cpue.csv")
write_csv(mock_data, out_path)
cat("\nSaved:", out_path, "\n")
